version: "3.7"
services:
  jekyll-admin:
    build:
      context: .
    volumes:
      - ./src:/usr/src/jekyll-admin/src
      - ./spec:/usr/src/jekyll-admin/spec
    ports:
      - 4000:4000
      - 3000:3000
    command: script/server-frontend
volumes:
  node_modules:
